@transformation/d_bdt_ventes.sql
@transformation/d_bdt_ventes_body.sql
@transformation/d_bdt_card.sql
@transformation/d_bdt_card_body.sql
@transformation/d_bdt_clerk.sql
@transformation/d_bdt_clerk_body.sql
@transformation/d_bdt_date.sql
@transformation/d_bdt_date_body.sql
@transformation/d_bdt_jolitre.sql
@transformation/d_bdt_jolitre_body.sql
@transformation/d_bdt_seg_functions.sql
