@transformation/f_bdt_catalogue.sql
@transformation/f_bdt_catalogue_body.sql
@transformation/f_bdt_date.sql
@transformation/f_bdt_date_body.sql
@transformation/f_bdt_marketing_view.sql
@transformation/f_bdt_magasin.sql
@transformation/f_bdt_magasin_body.sql
@transformation/f_bdt_ventes.sql
@transformation/f_bdt_ventes_body.sql
