@extraction/d_bde_dirs.sql
@extraction/d_bde_house.sql
@extraction/d_bde_occupation.sql
@extraction/d_bde_card.sql
@extraction/d_bde_cities.sql
@extraction/d_bde_clerk.sql
@extraction/d_bde_dune_corp.sql
@extraction/d_bde_jolitres.sql
@extraction/d_bde_sectors.sql
@extraction/d_bde_store.sql
@extraction/d_bde_temperature.sql
